server:
  port: 7771
# 设置暴露所有端点
# management.endpoints.web.exposure.include=*
# 设置单个端点（/shutdown）可用
#management.endpoint.shutdown.enabled=true
# 设置暴露所有端点，除了env
# management.endpoints.web.exposure.include=*
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
management:
  endpoint:
    refresh:
      enabled: true
# management.endpoints.web.exposure.exclude=env