server:
  port: 2221
spring:
  application:
    name: eureka-client-consumer
eureka:
  client:
    instance:
      instance-id: tear2122
      prefer-ip-address: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
info:
  app.name: tearsmart