server:
  port: 5550
spring:
  application:
    name: hystrix-client
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
#actuator端口
management:
#  server:
#    port: 9007
  endpoints:
    web:
#      base-path: /monitor #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点
