server:
  port: 5550
spring:
  application:
    name: hystrix-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
#springCloud C版本之后feign关联hystrix实现熔断默认关闭,使用的时候需要配置打开.
feign:
  hystrix:
    enabled: true
#actuator端口
#management:
#  #  server:
#  #    port: 9007
#  endpoints:
#    web:
#      #      base-path: /monitor #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
#      exposure:
#        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点
#====================================================================
# 解决第一次请求报超时异常的方案，因为 hystrix 的默认超时时间是 1 秒，因此请求超过该时间后，就会出现页面超时显示 ：
#
# 这里就介绍大概三种方式来解决超时的问题，解决方案如下：
#
# 第一种方式：将 hystrix 的超时时间设置成 5000 毫秒
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2000
#
# 或者：
# 第二种方式：将 hystrix 的超时时间直接禁用掉，这样就没有超时的一说了，因为永远也不会超时了
# hystrix.command.default.execution.timeout.enabled: false
#
# 或者：
# 第三种方式：索性禁用feign的hystrix支持
# feign.hystrix.enabled: false ## 索性禁用feign的hystrix支持

# 超时的issue：https://github.com/spring-cloud/spring-cloud-netflix/issues/768
# 超时的解决方案： http://stackoverflow.com/questions/27375557/hystrix-command-fails-with-timed-out-and-no-fallback-available
# hystrix配置： https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds
#hystrix的超时时间
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 1000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000