spring:
  application:
    name: eureka-client-provide
server:
  port: 2220
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    instance-id: eureka-client-provide