spring:
  application:
    name: eureka-client-provide
server:
  port: 2220
eureka:
  instance:
    hostname: client-provide
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true