server:
  port: 8761
eureka:
  environment: practice
  instance:
    hostname: eureka-server
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
#      defaultZone: http://root:root@localhost:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true
#  server:
#    enable-self-preservation: true

spring:
  security:
    user:
      name: root
      password: root
my:
  name:
    first: liu
    two: yl