server:
  port: 8763
eureka:
  environment: practice
  instance:
    hostname: eureka-server-8763
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  healthcheck:
    enabled: true
#  server:
#    enable-self-preservation: true

spring:
  security:
    user:
      name: root
      password: root
