server:
  port: 4440
spring:
  application:
    name: service-feign
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka

spring-cloud-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.tearsmart.feign.config.RoundRobinRule