server:
  port: 4440
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
#
#spring-cloud-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.tearsmart.feign.config.RoundRobinRule
