server:
  port: 6660
spring:
  application:
    name: zuul-client
eureka:
  client:
    serverUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: tear-smart.com:6660
info:
  app.name: zuul-client
  author.name: tear-smart
  build.artifacted: $project.artifactId$
  build.version: '@project.modelVersion@'
zuul:
  routes:
    provide-client:
      path: /provide-client/**
      serviceId: eureka-client-provide
      stripPrefix: false