server:
  port: 6660
spring:
  application:
    name: zuul-client
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    eureka-client-provide: /*